In [2]:
import pandas as pd
from sqlalchemy import create_engine

In [4]:
#read the CSV
df_game_data = pd.read_csv("game_database_final.csv")
df_game_data.head()

,Game,Month,Hours Watched,Hours Gained,% Hour Gained,Average Viewers,Viewers Gained,% Viewers Gained,Peak Concurrent Viewers,Average Concurrent Streams,Concurrent Streams Gain,% Concurrent Streans Gain,Peak Concurrent Streams
0,Among Us,01/01/21,27.1M,-23.2M,-46.10%,42.0K,"-25,759",-38%,269K,895,-312,-25.80%,2.4K
1,Among Us,12/01/20,50.3M,-26.7M,-34.70%,67.7K,"-39,400",-36.80%,499K,1.2K,-641,-34.70%,3.3K
2,Among Us,11/01/20,77.0M,-32.6M,-29.70%,107K,"-40,281",-27.30%,774K,1.8K,"-1,058",-36.40%,5.3K
3,Among Us,10/01/20,83.4M,-63.5M,-43.20%,3.0K,-450,-12.90%,9.1K,151K,"-53,045",-26%,754K
4,Among Us,09/01/20,147M,+116M,380%,3.5K,"2,985",598%,12.4K,204K,"162,989",396%,743K